<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:matterhorn="http://docuteam.ch/matterhorn"
           xmlns="ch:docuteam:mapping:csv" targetNamespace="ch:docuteam:mapping:csv"
    elementFormDefault="qualified">

    <xs:include schemaLocation="csv-format.xsd"/>

    <xs:import
            namespace="http://docuteam.ch/matterhorn"
            schemaLocation="matterhorn-field-type.xsd"/>

    <xs:element name="importTableConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="csvFormat"/>
                <xs:element name="checkAllLines" type="xs:boolean" default="false" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Check that all lines of the CSV file are referencing an existing node of the SIP.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="checkAllNodes" type="xs:boolean" default="false" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Check that all nodes of the SIP are referenced in the CSV file.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="existingValues" type="existingValueType" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Indicate how to handle existing values:
- skip: ignore the value from the CSV file.
- overwrite: replace existing values with values (if existing) from the CSV file.
- add: keep the existing value and add the value from the CSV file as an additional field.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:choice>
                    <xs:element name="referenceColumnNumber" type="xs:integer">
                        <xs:annotation>
                            <xs:documentation>Indicate the number of the column containing the references (relative paths) to the nodes within the SIP.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="referenceColumnLabel" type="xs:NMTOKEN">
                        <xs:annotation>
                            <xs:documentation>Indicate the label of the column containing the references (relative paths) to the nodes within the SIP.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:choice>
                <xs:element ref="columnMapping" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="existingValueType">
        <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="skip"/>
            <xs:enumeration value="overwrite"/>
            <xs:enumeration value="add"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="columnMapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="column" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="column">
        <xs:annotation>
            <xs:documentation>Specify a mapping indicating the header of a column from the CSV file and an accessorID from the Matterhorn METS standard (referring an EAD element).</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="tableHeaderLabel" use="required" type="xs:string"/>
            <xs:attribute name="matterhornMetsAccessorID" use="required" type="matterhorn:matterhornFieldType"/>
        </xs:complexType>
    </xs:element>

</xs:schema>
