<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ch.docuteam</groupId>
    <artifactId>docuteam</artifactId>
    <version>${revision}${sha1}${changelist}</version>
  </parent>

  <artifactId>${packer.artifactId.mac}</artifactId>
  <name>${app.name}</name>
  <packaging>pom</packaging>

  <properties>
    <!-- if you want to bundle JRE into the distribution, override and set this property to "false" in your individual configuration's pom.xml -->
    <skip-jre>false</skip-jre>
  </properties>

  <build>
    <resources>
      <resource>
        <directory>${project.basedir}/../docuteam-packer-dist/src/main/resources</directory>
      </resource>
      <resource>
        <directory>${project.basedir}/src/main/resources</directory>
      </resource>
      <resource>
        <directory>${project.basedir}/src/main/resources-filtered</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <executions>
          <execution>
            <id>default-resources</id>
            <phase>process-resources</phase>
            <goals>
              <goal>resources</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.googlecode.maven-download-plugin</groupId>
        <artifactId>download-maven-plugin</artifactId>
        <version>1.8.1</version>
        <executions>

          <!-- Download mac JDK -->
          <execution>
            <id>download-jdk-mac</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>wget</goal>
            </goals>
            <configuration>
              <url>https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.10%2B7/OpenJDK21U-jdk_x64_mac_hotspot_21.0.10_7.tar.gz</url>
              <outputDirectory>${project.build.directory}/jdks</outputDirectory>
              <outputFileName>jdk-21-mac.tar.gz</outputFileName>
              <cacheDirectory>${user.home}/.m2/jdk-cache</cacheDirectory>
              <sha256>7484d5d4cdb02fc17a842ab86ddac2524a0365066659c46b2e258c64152379cd</sha256>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>unpack-jdk-mac</id>
            <phase>generate-resources</phase>
            <goals><goal>run</goal></goals>
            <configuration>
              <target>
                <untar src="${project.build.directory}/jdks/jdk-21-mac.tar.gz"
                       dest="${project.build.directory}/jdks/mac"
                       compression="gzip"/>
              </target>
            </configuration>
          </execution>
          <execution>
            <id>rename-jdk-mac</id>
            <phase>generate-resources</phase>
            <goals><goal>run</goal></goals>
            <configuration>
              <target>
                <move todir="${project.build.directory}/jdks/mac/jdk">
                  <fileset dir="${project.build.directory}/jdks/mac">
                    <include name="jdk-*/Contents/Home/**"/>
                  </fileset>
                  <cutdirsmapper dirs="3"/>
                </move>
              </target>
            </configuration>
          </execution>
          <execution>
            <id>create-runtime-image-mac</id>
            <phase>prepare-package</phase>
            <goals><goal>run</goal></goals>
            <configuration>
              <target>
                <delete dir="${project.build.directory}/jre" failonerror="false"/>

                <chmod file="${project.build.directory}/jdks/mac/jdk/bin/*" perm="755"/>
                <chmod file="${project.build.directory}/jdks/mac/jdk/lib/jspawnhelper" perm="755" failonerror="false"/>
                <exec executable="${java.home}/bin/jlink"
                      failonerror="true">
                  <arg value="--module-path"/>
                  <arg value="${project.build.directory}/jdks/mac/jdk/jmods"/>
                  <arg value="--add-modules"/>
                  <arg value="java.base,java.compiler,java.datatransfer,java.desktop,java.logging,java.management,java.naming,java.net.http,java.prefs,java.rmi,java.scripting,java.security.jgss,java.security.sasl,java.sql,java.xml,jdk.security.auth,jdk.unsupported,jdk.xml.dom"/>
                  <arg value="--output"/>
                  <arg value="${project.build.directory}/jre"/>
                  <arg value="--compress=zip-9"/>
                  <arg value="--strip-debug"/>
                  <arg value="--no-header-files"/>
                  <arg value="--no-man-pages"/>
                </exec>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- create a packer distribution:
     mvn -pl docuteam-packer clean package assembly:single
     -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>${maven-assembly-plugin.plugin.version}</version>
        <configuration>
          <appendAssemblyId>false</appendAssemblyId>
          <!-- Configures the used assembly descriptor -->
          <descriptors>
            <descriptor>src/main/assembly/assembly.xml</descriptor>
          </descriptors>
        </configuration>
        <executions>
          <execution>
            <id>create-archive</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>ch.docuteam</groupId>
      <artifactId>${packer.branding.prefix}docuteam-packer</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>standard</id>
      <activation>
        <property>
          <name>!branding</name>
        </property>
      </activation>
      <properties>
        <app.name>docuteam packer distribution with jre bundled for macOS</app.name>
        <assembly.baseDirectory>docuteam packer</assembly.baseDirectory>
      </properties>
    </profile>

    <profile>
      <id>OCTAVE</id>
      <activation>
        <property>
          <name>branding</name>
          <value>octave</value>
        </property>
      </activation>
      <properties>
        <app.name>OCTAVE/docuteam packer distribution with jre bundled for macOS</app.name>
        <assembly.baseDirectory>octave</assembly.baseDirectory>
      </properties>
    </profile>
  </profiles>

</project>
